[workspace]
members = ["."]
resolver = "2"

[package]
name = "fractured-json-rs"
version = "0.1.0"
edition = "2021"
license = "Unlicense"

[dependencies]
jsonc-parser = { version = "0.24", features = ["cst"] }
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
